--INSERT INTO FoodItem VALUES ("Magere franse kwark");
--INSERT INTO FoodItem VALUES ("30+ Jong belegen kaas");
--INSERT INTO FoodItem VALUES ("Frikandelbroodje");
--INSERT INTO FoodItem VALUES ("Fuji appel");
--INSERT INTO FoodItem VALUES ("Banaan");
